[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

[server]
port = 3000
headless = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false